const CONFIG = {
    introTitle: 'Tíu ơi!',
    introDesc: `Anh hỏi em cái này nha `,
    btnIntro: 'Bé ơi',
    title: 'Bé ơi bé có yêu anh nhìu hong 😙',
    desc: 'Phải nói thiệt nhe ',
    btnYes: 'Vẫn yêu anh nhìu lém ',
    btnNo: 'Không, hết iu rui ',
    question:'Trên thế giới có 1 lon người mà sao em lại yêu anh dạ ',
    btnReply: 'Gửi cho chồng péo ',
    reply: 'Tại vì anh đẹp trai lém ',
    mess: 'Anh biết mà 🥰. Yêu Tú nhiềuuuuuuuu 😘😘 ',
    messDesc: 'Em đừng giận anh nữa nha cục cưng.',
    btnAccept: 'Hết giận nhe. Mặc dù hơi sến mà thui đừng giận anh nữa nhe mốt hết dịch chở đi ăn bánh gạo 79ka ',
}
